name: Code Review
on: [push]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm install
      - name: Run code review
        run: node review.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
